name: Update Icons JSON

on:
  push:
    branches:
      - main
      - feat/automate-icon-addition
  workflow_dispatch:

jobs:
  update-icons:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # native fetch supported

      - name: Update icons.json
        env:
          FIGMA_API_TOKEN: ${{ secrets.FIGMA_API_TOKEN }}
          FILE_ID: 'jubmQL9Z8V7881ayUD95ps'
          NODE_ID: '103317-3667'
        run: |
          node --input-type=module <<'EOF'
          const { writeFile, readFile, access } = await import('fs/promises');
          const { constants } = await import('fs');
          const path = 'packages/blade/scripts/icons.json';

          const token = process.env.FIGMA_API_TOKEN;
          const fileId = process.env.FILE_ID;
          const nodeId = process.env.NODE_ID;

          async function updateIconsJson(componentNames, svgData) {
            let iconsJson = [];

            try {
              await access(path, constants.F_OK);
              const data = await readFile(path, 'utf8');
              iconsJson = JSON.parse(data);
            } catch (e) {
              console.log('icons.json not found, creating a new one');
            }

            componentNames.forEach((name, index) => {
              const sanitizedName = name.replace(/[^a-z0-9]/gi, '_').toLowerCase();
              iconsJson.push({ [sanitizedName]: svgData[index] });
            });

            await writeFile(path, JSON.stringify(iconsJson, null, 2), 'utf8');
            console.log('Updated icons.json');
          }

          async function fetchComponentSVGs(componentIds, componentNames) {
            const res = await fetch(`https://api.figma.com/v1/images/${fileId}?ids=${componentIds.join(',')}&format=svg`, {
              headers: { 'X-Figma-Token': token }
            });

            const imageUrls = (await res.json()).images;
            const svgData = await Promise.all(componentIds.map(async (id) => {
              const svgRes = await fetch(imageUrls[id]);
              return await svgRes.text();
            }));

            await updateIconsJson(componentNames, svgData);
          }

          async function fetchNode() {
            const res = await fetch(`https://api.figma.com/v1/files/${fileId}/nodes?ids=${nodeId}`, {
              headers: { 'X-Figma-Token': token }
            });

            const nodeData = await res.json();
            const { nodes } = nodeData;
            const key = Object.keys(nodes)[0];
            const componentsToBeAdded = nodes[key].document.children;

            const componentIds = componentsToBeAdded.map(c => c.id);
            const componentNames = componentsToBeAdded.map(c => c.name);

            await fetchComponentSVGs(componentIds, componentNames);
          }

          await fetchNode();
          EOF
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add packages/blade/scripts/icons.json
          git commit -m 'Update icons.json with new SVGs'
    